[project]
name = "diffusion_policy_brawn"
description = "Diffusion Policy for running in the Brawn ecosystem."
requires-python = ">=3.12"
dynamic = ["version"]
version = "0.0.1"
dependencies = [
    "diffusers==0.30.3",
    "hydra-core==1.3.2",
    "pandas==2.2.3",
    "zarr==2.18.3",
]
